# Generated by Django 4.0.3 on 2022-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('root-admin', 'root-admin'), ('admin-organization', 'admin-organization'), ('just-person', 'just-person')], default='just-person', max_length=256),
        ),
    ]
