# Generated by Django 4.0.3 on 2022-04-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_options_remove_user_status_user_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ADMIN',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ROOT_ADMIN',
            new_name='is_root_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='WORKERS',
            new_name='is_worker',
        ),
    ]
